### ISSUE TITLE
 - SORRY, WRONG PROJECT - Not a QtTinySA issue - please delete ( run errors on Fedora 39 )

### ISSUE THREAD

**Issue by Zotter** [g4ixt/QtTinySA#48]
Note that Fedora 40 is due to be released by end of this month.

Downloaded latest tarball - unpacked and installed with "pip install ."

Start TinySASaver in terminal - received the following messages in terminal while the GUI screen displayed. Does not appear to affect operation.

"TinySASaver 0.2.2
Copyright (C) 2019 Rune B. Broberg
This program comes with ABSOLUTELY NO WARRANTY
This program is licensed under the GNU General Public License version 3

See https://github.com/erikkaashoek/tinysa-saver for further details
QSocketNotifier: Can only be used with threads started with QThread
Settings: /home/user/.config/TinySASaver/TinySASaver.ini
2024-04-16 18:33:32,751 - TinySASaver.TinySASaver - ERROR - Checking for updates produced an HTTP exception: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/home/<user>/.local/lib/python3.12/site-packages/TinySASaver/TinySASaver.py", line 1855, in findUpdates
    updates = json.load(request.urlopen(req, timeout=3))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/urllib/request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib64/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found"

**Comment by Zotter** [comment]
SORRY, WRONG PROJECT - Not a QtTinySA issue - please delete ( run errors on Fedora 39 )
